/** Model details — the one place technical identifiers are surfaced. */
export function ModelPage() {
  return (
    <div className="mx-auto max-w-[720px] px-4 py-9 lg:px-8">
      <h1 className="text-[20px] font-semibold tracking-[-0.01em] text-[var(--text-1)]">
        Model details
      </h1>
      <p className="mt-1 text-[12.5px] text-[var(--text-3)]">
        How projections and insights are produced.
      </p>

      <div className="mt-8 space-y-8">
        <section>
          <h2 className="mb-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-[var(--text-3)]">
            Projections
          </h2>
          <p className="text-[13px] leading-[1.7] text-[var(--text-2)]">
            Weekly full-PPR projections come from gradient-boosted tree models
            (XGBoost) trained on six seasons of NFL data. Every historical feature is
            shifted one week so a projection only sees information available before
            kickoff, and the model is evaluated with walk-forward validation — trained
            on the past, tested on the future, never shuffled.
          </p>
        </section>

        <section>
          <h2 className="mb-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-[var(--text-3)]">
            Accuracy
          </h2>
          <p className="mb-3 text-[13px] leading-[1.7] text-[var(--text-2)]">
            Mean absolute error on held-out weeks, in PPR points, versus a naive
            three-week-average baseline:
          </p>
          <table className="tbl max-w-[380px]">
            <thead>
              <tr>
                <th>Position</th>
                <th className="num">Model MAE</th>
                <th className="num">Naive MAE</th>
              </tr>
            </thead>
            <tbody>
              {[
                ['QB', '6.36', '7.19'],
                ['RB', '4.72', '5.09'],
                ['WR', '4.60', '5.13'],
                ['TE', '4.92', '5.45'],
                ['Overall', '4.88', '5.38'],
              ].map(([pos, model, naive]) => (
                <tr key={pos}>
                  <td className="text-[12.5px] text-[var(--text-2)]">{pos}</td>
                  <td className="num text-[12.5px] font-medium text-[var(--text-1)]">
                    {model}
                  </td>
                  <td className="num text-[12.5px] text-[var(--text-3)]">{naive}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <section>
          <h2 className="mb-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-[var(--text-3)]">
            Insights
          </h2>
          <p className="text-[13px] leading-[1.7] text-[var(--text-2)]">
            Written insights are generated by OpenAI's GPT-5.6 Terra from each
            player's projection and matchup context — Vegas lines, opponent defensive
            splits, recent form, venue, and weather. The model is constrained to the
            provided data and covers the top 15 projected players each week.
          </p>
        </section>

        <section>
          <h2 className="mb-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-[var(--text-3)]">
            Data
          </h2>
          <p className="text-[13px] leading-[1.7] text-[var(--text-2)]">
            Source data is public NFL play-by-play, schedules, snap counts, depth
            charts, and injury reports (nflverse), processed in Databricks and served
            from Delta tables. Projections are locked before games and scored against
            actual results postgame.
          </p>
        </section>
      </div>
    </div>
  )
}
